import{a as p,S as f,i as a}from"./assets/vendor-BDaiwwc1.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const g=async(t,s)=>{const i={params:{key:"48318728-33e02a537f20daf55b07c1f54",q:t.trim(),page:s,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:"true"}};try{return(await p.get("https://pixabay.com/api/",i)).data}catch(o){throw console.error("Error fetching data:",o.message),o}},y=({webformatURL:t,largeImageURL:s,tags:i,likes:o,views:e,comments:r,downloads:n})=>`
  <div class="photo-card">
    <a href="${s}" class="photo-link">
      <img src="${t}" alt="${i}" loading="lazy" />
    </a>
    <div class="info">
      <p><b>Likes:</b> ${o}</p>
      <p><b>Views:</b> ${e}</p>
      <p><b>Comments:</b> ${r}</p>
      <p><b>Downloads:</b> ${n}</p>
    </div>
  </div>`,b=document.querySelector(".js-search-form"),d=document.querySelector(".js-gallery"),m=document.querySelector(".js-loader"),l=document.querySelector(".js-load-more-btn");let c=1,u="";const L=new f(".js-gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});l.classList.add("is-hidden");const h=()=>{m.style.display="block",g(u,c).then(t=>{if(!t.hits||t.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const s=t.hits.map(o=>y(o)).join("");d.insertAdjacentHTML("beforeend",s),t.totalHits>c*t.hits.length?l.classList.remove("is-hidden"):l.classList.add("is-hidden"),L.refresh(),a.success({title:"Success",message:`Found ${t.totalHits||0} images.`});const{height:i}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}).catch(t=>{console.error("Error fetching photos:",t),a.error({title:"Error",message:"Something went wrong. Please try again later!"})}).finally(()=>{m.style.display="none"})},E=t=>{if(t.preventDefault(),d.innerHTML="",c=1,u=t.currentTarget.elements.user_query.value.trim(),u===""){a.error({title:"Error",message:"Please fill in the search form!"});return}h()},S=()=>{c+=1,h()};b.addEventListener("submit",E);l.addEventListener("click",S);
//# sourceMappingURL=index.js.map
