import{a as f,S as g,i as l}from"./assets/vendor-BDaiwwc1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const y=async(o,t)=>{const i={params:{key:"48318728-33e02a537f20daf55b07c1f54",q:o.trim(),page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:"true"}};try{return(await f.get("https://pixabay.com/api/",i)).data}catch(s){throw console.error("Error fetching data:",s.message),s}},b=({webformatURL:o,largeImageURL:t,tags:i,likes:s,views:e,comments:r,downloads:n})=>`
  <div class="photo-card">
    <a href="${t}" class="photo-link">
      <img src="${o}" alt="${i}" loading="lazy" />
    </a>
    <div class="info">
      <p><b>Likes:</b> ${s}</p>
      <p><b>Views:</b> ${e}</p>
      <p><b>Comments:</b> ${r}</p>
      <p><b>Downloads:</b> ${n}</p>
    </div>
  </div>`,L=document.querySelector(".js-search-form"),u=document.querySelector(".js-gallery"),m=document.querySelector(".js-loader"),a=document.querySelector(".js-load-more-btn");let d=1,h="",c=0;const E=new g(".js-gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});a.classList.add("is-hidden");const p=(o=!1)=>{m.style.display="block",y(h,d).then(t=>{if(!t.hits||t.hits.length===0){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),a.classList.add("is-hidden");return}const i=t.hits.map(e=>b(e)).join("");u.insertAdjacentHTML("beforeend",i),c=t.totalHits,o&&l.success({title:"Success",message:`Found ${c} images.`}),d*15>=c?(a.classList.add("is-hidden"),l.info({title:"Info",message:"You have reached the end of search results."})):a.classList.remove("is-hidden"),E.refresh();const{height:s}=u.firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}).catch(t=>{console.error("Error fetching photos:",t),l.error({title:"Error",message:"Something went wrong. Please try again later!"})}).finally(()=>{m.style.display="none"})},v=o=>{if(o.preventDefault(),u.innerHTML="",d=1,c=0,h=o.currentTarget.elements.user_query.value.trim(),h===""){l.error({title:"Error",message:"Please enter a search term!"}),a.classList.add("is-hidden");return}p(!0)},S=()=>{d+=1,p()};L.addEventListener("submit",v);a.addEventListener("click",S);
//# sourceMappingURL=index.js.map
